language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:phpcr:init:dbal --force
  - php app/console doctrine:phpcr:workspace:create standard_test
  - php app/console doctrine:phpcr:repository:init -e=test

script: phpunit -c app

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
