imports:
    - { resource: config_dev.yml }

app.config:
    error_handler: false
    test:  ~

zend.config:
    logger:
        priority: debug

webprofiler.config:
    toolbar: false
    intercept_redirects: false

zend.config:
    logger:
        priority: debug