parameters:
    kernel.include_core_classes: false

frontend.config:  ~

app.config:
    charset:             UTF-8
    error_handler:       null
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:
        enabled: true
    templating:
        escaping:       htmlspecialchars
    user:
        session:
            lifetime: 2592000 # one month

twig.config:
    auto_reload: true
