parameters:
    database_driver: pdo_sqlite
    database_path: '%kernel.root_dir%/app.sqlite'
    phpcr_backend:
        type: doctrinedbal
        connection: default
        caches:
            meta: doctrine_cache.providers.phpcr_meta
            nodes: doctrine_cache.providers.phpcr_nodes
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
    database_host: null
    database_port: null
    database_name: null
    database_user: null
    database_password: null
