# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal



#TODO: use that import?
#<import resource=”symfony_cmf_create.rest.controller” type=”rest” />

#createjs:
#    resource: “@SymfonyCmfCreateBundle/Resources/config/routing/rest.xml”

