# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

create:
    resource: "@SymfonyCmfCreateBundle/Resources/config/routing/rest.xml"
create_iamge:
    resource: "@SymfonyCmfCreateBundle/Resources/config/routing/image.xml"

