# added to get the security.context service for the publish workflow
# see https://github.com/symfony-cmf/CoreBundle/issues/104
security:

    providers:
        in_memory:
            memory:
                users:

    firewalls:

        main:
            pattern: ^/
            anonymous: ~
            http_basic:

