services:
    app.block.events:
        class: AppBundle\Block\EventsBlockService
        arguments:
            - app.block.events
            - @templating
            - null
            - @doctrine_phpcr.odm.document_manager
            - @cmf_core.publish_workflow.checker
        tags:
            - {name: "sonata.block"}
    cmf_simple_cms.persistence.phpcr.menu_provider:
      class: AppBundle\Menu\MenuProvider
      arguments:
        - @cmf_menu.loader.node
        - @doctrine_phpcr
        - %cmf_simple_cms.persistence.phpcr.menu_basepath%
      tags:
        - {name: knp_menu.provider, request: true}
      calls:
        - [ setManagerName, [ %cmf_simple_cms.persistence.phpcr.manager_name% ] ]
        - [ setFactory, [ @cmf_menu.factory.quiet ] ]
