services:
  cmf_menu.provider:
        class: Cmf\MainBundle\Menu\MenuProvider
        arguments:
          - @service_container
          - @cmf_menu.factory
          - %cmf_menu.document_manager_name%
          - %cmf_menu.menu_basepath%
        tags:
          - { name: knp_menu.provider, alias: simple } # The alias is what is used to retrieve the menu