homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Main:index }

homepage2:
    pattern:  /slides.html
    defaults: { _controller: FrontendBundle:Main:index }

get_involved:
    pattern:  /get-involved
    defaults: { _controller: FrontendBundle:Main:getInvolved }

about:
    pattern:  /about
    defaults: { _controller: FrontendBundle:Main:about }
