homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Main:index }

slides:
    pattern:  /slides.html
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true # this for 301

get_started:
    pattern:  /get-started
    defaults: { _controller: FrontendBundle:Main:getStarted }

get_involved:
    pattern:  /get-involved
    defaults: { _controller: FrontendBundle:Main:getInvolved }

news:
    pattern:  /news
    defaults: { _controller: FrontendBundle:Main:news }

about:
    pattern:  /about
    defaults: { _controller: FrontendBundle:Main:about }
