homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Main:index }

slides:
    pattern:  /slides.html
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true # this for 301

get_involved:
    pattern:  /get-involved
    defaults: { _controller: FrontendBundle:Main:getInvolved }

about:
    pattern:  /about
    defaults: { _controller: FrontendBundle:Main:about }
